### ISSUE TITLE
Exercise 4.3.4

### ISSUE THREAD

**Issue by dcgreaves** [jrnold/e4qf#8]
If x = Inf, then x * 0 = NaN. That's why NA * 0 is missing, I believe.

**Comment by jrnold** [comment]
Good point. I had forgot to think about Inf.

**Comment by jrnold** [comment]
Thanks! 

Since this is an issue with the question in *R for Data Science* which mentions it as a "tricky counterexample", you should probably open an issue with repo of the text: https://github.com/hadley/r4ds so it can be fixed for next edition or added as errata.
